package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Articulo generated by hbm2java
 */
@Entity
@Table(name="articulo"
    ,catalog="proyecto"
)
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private Categoria categoria;
     private String nombreArticulo;
     private double precio;

    public Articulo() {
    }

    public Articulo(Categoria categoria, String nombreArticulo, double precio) {
       this.categoria = categoria;
       this.nombreArticulo = nombreArticulo;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idArticulo", unique=true, nullable=false)
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCategoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="nombreArticulo", nullable=false, length=45)
    public String getNombreArticulo() {
        return this.nombreArticulo;
    }
    
    public void setNombreArticulo(String nombreArticulo) {
        this.nombreArticulo = nombreArticulo;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }




}


