package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Asiento generated by hbm2java
 */
@Entity
@Table(name="asiento"
    ,catalog="proyecto"
)
public class Asiento  implements java.io.Serializable {


     private Integer idAsiento;
     private Sala sala;
     private String numAsiento;
     private boolean disponibilidad;

    public Asiento() {
    }

    public Asiento(Sala sala, String numAsiento, boolean disponibilidad) {
       this.sala = sala;
       this.numAsiento = numAsiento;
       this.disponibilidad = disponibilidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAsiento", unique=true, nullable=false)
    public Integer getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(Integer idAsiento) {
        this.idAsiento = idAsiento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSala", nullable=false)
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }

    
    @Column(name="numAsiento", nullable=false, length=3)
    public String getNumAsiento() {
        return this.numAsiento;
    }
    
    public void setNumAsiento(String numAsiento) {
        this.numAsiento = numAsiento;
    }

    
    @Column(name="disponibilidad", nullable=false)
    public boolean isDisponibilidad() {
        return this.disponibilidad;
    }
    
    public void setDisponibilidad(boolean disponibilidad) {
        this.disponibilidad = disponibilidad;
    }




}


