package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entidadfederativa generated by hbm2java
 */
@Entity
@Table(name="entidadfederativa"
    ,catalog="proyecto"
)
public class Entidadfederativa  implements java.io.Serializable {


     private Integer idEntidadFederativa;
     private String nombreEntidadFederativa;
     private Set delegacionmunicipios = new HashSet(0);

    public Entidadfederativa() {
    }

	
    public Entidadfederativa(String nombreEntidadFederativa) {
        this.nombreEntidadFederativa = nombreEntidadFederativa;
    }
    public Entidadfederativa(String nombreEntidadFederativa, Set delegacionmunicipios) {
       this.nombreEntidadFederativa = nombreEntidadFederativa;
       this.delegacionmunicipios = delegacionmunicipios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEntidadFederativa", unique=true, nullable=false)
    public Integer getIdEntidadFederativa() {
        return this.idEntidadFederativa;
    }
    
    public void setIdEntidadFederativa(Integer idEntidadFederativa) {
        this.idEntidadFederativa = idEntidadFederativa;
    }

    
    @Column(name="nombreEntidadFederativa", nullable=false, length=45)
    public String getNombreEntidadFederativa() {
        return this.nombreEntidadFederativa;
    }
    
    public void setNombreEntidadFederativa(String nombreEntidadFederativa) {
        this.nombreEntidadFederativa = nombreEntidadFederativa;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entidadfederativa")
    public Set getDelegacionmunicipios() {
        return this.delegacionmunicipios;
    }
    
    public void setDelegacionmunicipios(Set delegacionmunicipios) {
        this.delegacionmunicipios = delegacionmunicipios;
    }




}


