package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="horario"
    ,catalog="proyecto"
)
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private String horario;
     private Set salahorarios = new HashSet(0);

    public Horario() {
    }

	
    public Horario(String horario) {
        this.horario = horario;
    }
    public Horario(String horario, Set salahorarios) {
       this.horario = horario;
       this.salahorarios = salahorarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idHorario", unique=true, nullable=false)
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    
    @Column(name="horario", nullable=false, length=10)
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="horario")
    public Set getSalahorarios() {
        return this.salahorarios;
    }
    
    public void setSalahorarios(Set salahorarios) {
        this.salahorarios = salahorarios;
    }




}


