package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name="pelicula"
    ,catalog="proyecto"
)
public class Pelicula  implements java.io.Serializable {


     private Integer idPelicula;
     private Genero genero;
     private String nombrePelicula;
     private int duracion;
     private String resumen;
     private String clasificacion;
     private Set salas = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(String nombrePelicula, int duracion, String resumen) {
        this.nombrePelicula = nombrePelicula;
        this.duracion = duracion;
        this.resumen = resumen;
    }
    public Pelicula(Genero genero, String nombrePelicula, int duracion, String resumen, String clasificacion, Set salas) {
       this.genero = genero;
       this.nombrePelicula = nombrePelicula;
       this.duracion = duracion;
       this.resumen = resumen;
       this.clasificacion = clasificacion;
       this.salas = salas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPelicula", unique=true, nullable=false)
    public Integer getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(Integer idPelicula) {
        this.idPelicula = idPelicula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGenero")
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }

    
    @Column(name="nombrePelicula", nullable=false, length=45)
    public String getNombrePelicula() {
        return this.nombrePelicula;
    }
    
    public void setNombrePelicula(String nombrePelicula) {
        this.nombrePelicula = nombrePelicula;
    }

    
    @Column(name="duracion", nullable=false)
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }

    
    @Column(name="resumen", nullable=false, length=65535)
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    
    @Column(name="clasificacion", length=3)
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pelicula")
    public Set getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set salas) {
        this.salas = salas;
    }




}


