package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name="sala"
    ,catalog="proyecto"
)
public class Sala  implements java.io.Serializable {


     private Integer idSala;
     private Pelicula pelicula;
     private Tiposala tiposala;
     private int numeroFilas;
     private int numeroAsientos;
     private Set asientos = new HashSet(0);
     private Set salahorarios = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int numeroFilas, int numeroAsientos) {
        this.numeroFilas = numeroFilas;
        this.numeroAsientos = numeroAsientos;
    }
    public Sala(Pelicula pelicula, Tiposala tiposala, int numeroFilas, int numeroAsientos, Set asientos, Set salahorarios) {
       this.pelicula = pelicula;
       this.tiposala = tiposala;
       this.numeroFilas = numeroFilas;
       this.numeroAsientos = numeroAsientos;
       this.asientos = asientos;
       this.salahorarios = salahorarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSala", unique=true, nullable=false)
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPelicula")
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoSala")
    public Tiposala getTiposala() {
        return this.tiposala;
    }
    
    public void setTiposala(Tiposala tiposala) {
        this.tiposala = tiposala;
    }

    
    @Column(name="numeroFilas", nullable=false)
    public int getNumeroFilas() {
        return this.numeroFilas;
    }
    
    public void setNumeroFilas(int numeroFilas) {
        this.numeroFilas = numeroFilas;
    }

    
    @Column(name="numeroAsientos", nullable=false)
    public int getNumeroAsientos() {
        return this.numeroAsientos;
    }
    
    public void setNumeroAsientos(int numeroAsientos) {
        this.numeroAsientos = numeroAsientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set asientos) {
        this.asientos = asientos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sala")
    public Set getSalahorarios() {
        return this.salahorarios;
    }
    
    public void setSalahorarios(Set salahorarios) {
        this.salahorarios = salahorarios;
    }




}


