package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Salahorario generated by hbm2java
 */
@Entity
@Table(name="salahorario"
    ,catalog="proyecto"
)
public class Salahorario  implements java.io.Serializable {


     private Integer idSalaHorario;
     private Horario horario;
     private Sala sala;

    public Salahorario() {
    }

    public Salahorario(Horario horario, Sala sala) {
       this.horario = horario;
       this.sala = sala;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSalaHorario", unique=true, nullable=false)
    public Integer getIdSalaHorario() {
        return this.idSalaHorario;
    }
    
    public void setIdSalaHorario(Integer idSalaHorario) {
        this.idSalaHorario = idSalaHorario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHorario", nullable=false)
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSala", nullable=false)
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }




}


