package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name="sucursal"
    ,catalog="proyecto"
)
public class Sucursal  implements java.io.Serializable {


     private Integer idSucursal;
     private Delegacionmunicipio delegacionmunicipio;
     private String nombreSucursal;
     private String calle;
     private int numero;
     private String codigoPostal;
     private String colonia;
     private Set usuarios = new HashSet(0);

    public Sucursal() {
    }

	
    public Sucursal(Delegacionmunicipio delegacionmunicipio, String nombreSucursal, String calle, int numero, String codigoPostal, String colonia) {
        this.delegacionmunicipio = delegacionmunicipio;
        this.nombreSucursal = nombreSucursal;
        this.calle = calle;
        this.numero = numero;
        this.codigoPostal = codigoPostal;
        this.colonia = colonia;
    }
    public Sucursal(Delegacionmunicipio delegacionmunicipio, String nombreSucursal, String calle, int numero, String codigoPostal, String colonia, Set usuarios) {
       this.delegacionmunicipio = delegacionmunicipio;
       this.nombreSucursal = nombreSucursal;
       this.calle = calle;
       this.numero = numero;
       this.codigoPostal = codigoPostal;
       this.colonia = colonia;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSucursal", unique=true, nullable=false)
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDelegacionMunicipio", nullable=false)
    public Delegacionmunicipio getDelegacionmunicipio() {
        return this.delegacionmunicipio;
    }
    
    public void setDelegacionmunicipio(Delegacionmunicipio delegacionmunicipio) {
        this.delegacionmunicipio = delegacionmunicipio;
    }

    
    @Column(name="nombreSucursal", nullable=false, length=100)
    public String getNombreSucursal() {
        return this.nombreSucursal;
    }
    
    public void setNombreSucursal(String nombreSucursal) {
        this.nombreSucursal = nombreSucursal;
    }

    
    @Column(name="calle", nullable=false, length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

    
    @Column(name="codigoPostal", nullable=false, length=5)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="colonia", nullable=false, length=45)
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sucursal")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


