package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipousuario generated by hbm2java
 */
@Entity
@Table(name="tipousuario"
    ,catalog="proyecto"
)
public class Tipousuario  implements java.io.Serializable {


     private Integer idTipoUsuario;
     private String descTipoUsuario;
     private Set usuarios = new HashSet(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String descTipoUsuario) {
        this.descTipoUsuario = descTipoUsuario;
    }
    public Tipousuario(String descTipoUsuario, Set usuarios) {
       this.descTipoUsuario = descTipoUsuario;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoUsuario", unique=true, nullable=false)
    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }

    
    @Column(name="descTipoUsuario", nullable=false, length=45)
    public String getDescTipoUsuario() {
        return this.descTipoUsuario;
    }
    
    public void setDescTipoUsuario(String descTipoUsuario) {
        this.descTipoUsuario = descTipoUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipousuario")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


