package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tiposala generated by hbm2java
 */
@Entity
@Table(name="tiposala"
    ,catalog="proyecto"
)
public class Tiposala  implements java.io.Serializable {


     private Integer idTipoSala;
     private String nombreTipoSala;
     private double precio;
     private Set salas = new HashSet(0);

    public Tiposala() {
    }

	
    public Tiposala(String nombreTipoSala, double precio) {
        this.nombreTipoSala = nombreTipoSala;
        this.precio = precio;
    }
    public Tiposala(String nombreTipoSala, double precio, Set salas) {
       this.nombreTipoSala = nombreTipoSala;
       this.precio = precio;
       this.salas = salas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idTipoSala", unique=true, nullable=false)
    public Integer getIdTipoSala() {
        return this.idTipoSala;
    }
    
    public void setIdTipoSala(Integer idTipoSala) {
        this.idTipoSala = idTipoSala;
    }

    
    @Column(name="nombreTipoSala", nullable=false, length=45)
    public String getNombreTipoSala() {
        return this.nombreTipoSala;
    }
    
    public void setNombreTipoSala(String nombreTipoSala) {
        this.nombreTipoSala = nombreTipoSala;
    }

    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tiposala")
    public Set getSalas() {
        return this.salas;
    }
    
    public void setSalas(Set salas) {
        this.salas = salas;
    }




}


