package com.ipn.mx.clases;
// Generated 5/01/2016 03:54:42 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="proyecto"
)
public class Usuario  implements java.io.Serializable {


     private String email;
     private Sucursal sucursal;
     private Tipousuario tipousuario;
     private String nombre;
     private String apPaterno;
     private String apMaterno;
     private byte[] contrasena;
     private double salario;
     private String genero;
     private int edad;

    public Usuario() {
    }

    public Usuario(String email, Sucursal sucursal, Tipousuario tipousuario, String nombre, String apPaterno, String apMaterno, byte[] contrasena, double salario, String genero, int edad) {
       this.email = email;
       this.sucursal = sucursal;
       this.tipousuario = tipousuario;
       this.nombre = nombre;
       this.apPaterno = apPaterno;
       this.apMaterno = apMaterno;
       this.contrasena = contrasena;
       this.salario = salario;
       this.genero = genero;
       this.edad = edad;
    }
   
     @Id 

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idSucursal", nullable=false)
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoUsuario", nullable=false)
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apPaterno", nullable=false, length=45)
    public String getApPaterno() {
        return this.apPaterno;
    }
    
    public void setApPaterno(String apPaterno) {
        this.apPaterno = apPaterno;
    }

    
    @Column(name="apMaterno", nullable=false, length=45)
    public String getApMaterno() {
        return this.apMaterno;
    }
    
    public void setApMaterno(String apMaterno) {
        this.apMaterno = apMaterno;
    }

    
    @Column(name="contrasena", nullable=false)
    public byte[] getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(byte[] contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="salario", nullable=false, precision=22, scale=0)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }

    
    @Column(name="genero", nullable=false, length=9)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


